### PR TITLE
Update non-production code to fix specs against Rails edge

### LINKED ISSUE #142: Specs do not pass against Rails edge
Ref: https://github.com/jsonapi-rb/jsonapi-rails/actions/runs/4275332544/jobs/7442603511

Bisected to: rails/rails@e65d41a47af0c56cb2d60868e6ad2ba01d324d48 rails/rails#45957

This will be fixed after the release of rspec/rspec-rails#2631

### PR DESCRIPTION
**Pull request by tagliala**
- No changes to production code
- Updates rspec-rails to close #142
- Fix specs against Rails edge
- Fix deprecation in Rails edge

### CODE REVIEW

File: spec/render_jsonapi_errors_spec.rb [hunk 1]
```diff
@@ -17,7 +17,7 @@
     {
       'errors' => [
         {
-          'detail' => 'Name can\'t be blank',
+          'detail' => "Name #{I18n.t('errors.messages.blank')}",
```
Comment (remear) [inline spec/render_jsonapi_errors_spec.rb:20]: A couple of questions here.

- Was the lack of localization causing failures?
- I don't see a locale file that defines `errors.messages.blank`. Is this a bult-in from `I18n`? Should we start including a locale file to use in these tests?

Comment (remear) [reply spec/render_jsonapi_errors_spec.rb:20]: Ah, the extended commit messages clear up most of what I was wondering.
